services:
  sales-airflow:
    container_name: retail_airflow
    image: sales-airflow:latest
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8080:8080"
    user: "${UID}:${GID}"
    environment:
      - AIRFLOW_UID=${UID}
    command: >
      bash -c "
      mkdir -p /opt/airflow/logs /opt/airflow/dags /opt/airflow/plugins &&
      chmod -R 777 /opt/airflow &&
      airflow standalone
      "
  postgres:
    container_name: retail_database
    image: postgres:latest
    environment:
      POSTGRES_USER: database
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: database
    ports:
      - "5000:5432" 
    volumes:
      - ./postgresql_data:/docker-entrypoint-initdb.d
      - ./database:/var/lib/postgresql/data
    restart: always


volumes:
  postgres: 

